import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar";

import { ThemeProvider } from "@/utils/ThemeContext";
import BackgroundVideos from "@/components/BackgroundVideos";

const mona_Sans = Mona_Sans({
  variable: "--font-mono_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <meta name="theme-color" content="#ffffff" />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const userPreference = localStorage.getItem('theme');
                const systemPreference = window.matchMedia('(prefers-color-scheme: dark)').matches;
                const theme = userPreference || (systemPreference ? 'dark' : 'light');
                document.documentElement.classList.toggle('dark', theme === 'dark');
              })();
            `,
          }}
        />
      </head>
      <body className={`${mona_Sans.className} antialiased`}>
        <ThemeProvider>
          {/* Background Videos */}
          <BackgroundVideos />

          <Navbar />
          {children}
          <div id="modal-root"></div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
