import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import { ThemeProvider } from "@/utils/ThemeContext";
import { ToastContainer } from "@/components/ui/toast";
import BackgroundAnimations from "@/components/backgroundAnimations";



const mona_Sans = Mona_Sans({
  variable: "--font-mono_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#ffffff" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
       <script
      dangerouslySetInnerHTML={{
        __html: `
          (function() {
            const userPreference = localStorage.getItem("theme");
            let theme = "light";

            if (userPreference) {
              theme = userPreference;
            } else {
              const systemPrefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
              theme = systemPrefersDark ? "dark" : "light";
            }

            document.documentElement.classList.toggle("dark", theme === "dark");
          })();
        `,
      }}
    />
      </head>
      <body className={`${mona_Sans.className} antialiased`}>
        <ThemeProvider>
          {/* Background Videos */}
          {/* <BackgroundVideos /> */}
          <BackgroundAnimations />
          <Navbar />
            <ToastContainer />
          {children}
          <div id="modal-root">
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
